#+TITLE: Spanish Basics
#+AUTHOR: Zhenkai Weng
#+DATE: 2020-08-30
#+BEGIN_OPTIONS
#+STARTUP: hideblocks
#+STARTUP: overview
#+OPTIONS: \n:t
#+HUGO_BASE_DIR: .
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_SECTION: wiki
#+HUGO_TAGS: usage
#+END_OPTIONS

Here's some /essential/ knowledge to kick-start your Spanish learning journey! This lesson is fairly long, so feel free to take breaks in between. You are expected to look up words you do not know in a [[https://www.spanishdict.com/][dictionary]].
* Spanish Alphabet (/el abecedario/)
Spanish uses the latin alphabet (a-z) plus some Spanish-only letters. Below is the Spanish alphabet and what they are called in Spanish. You should watch this [[https://www.youtube.com/watch?v=Vudw7GtB034][short video]] to learn about the pronunciation.
- a: /la a/
- b: /la be/
- c: /la ce/
- d: /la de/
- e: /la e/
- f: /la efe/
- g: /la /ge/ (h sound)
- h: /la hache/ (silent)
- i: /la i/ (pl. las íes) (long /e/ sound; see video)
- j: /la jota/ (h sound)
- k: /la ka/
- l: /la ele/
- m: /la eme/
- n: /la ene/
- ñ: /la eñe/ (ñ = ni)
- o: /la o/ (see video)
- p: /la pe/
- q: /la cu/
- r: /la erre/ (pronounced like "l" between vowels, otherwise roll the r)
- s: /la ese/
- t: /la te/
- u: /la u/ ("ooh" sound; see video)
- v: /la uve/
- w: /la uve doble/ (lit. double v)
- x: /la equis/
- y: /la i griega/ (lit. the Greek "i")
- z: /la zeta/ (pronounced "s")
- ch: /la che/
- gu (pronounced like "g" in English)
- ll (pronounced like "y" in English)
- qu (pronounced like "k" in English; "voiceless velar plosive"; see video)
- rr: /la erre doble/ / /doble erre/ (roll the r)
* Stress & Accents
Stressed syllables are pronounced slightly louder, a bit longer, and higher in pitch than other syllables, e.g. "a" in /dance/ and "u" in /butterfly/. In Spanish, the second-to-last syllable will be /stressed/ unless indicated otherwise by an accent (´), e.g. "i" in /la comida/ and "é" in /el teléfono/. If the word ends in a consonant (i.e. not any of a, e, i, o, u), then the last syllable is stressed unless the consonant is /n/ or /s/, e.g. "u" in /ayuda/, "e" in /carnet/, "ue" in /fueron/, and the last "i" in escribir.

To pronounce Spanish correctly, you also need to know the difference between strong & weak vowels. The strong Spanish vowels are a, e, and o. When two strong vowels are next to each other, they are pronounced as two separate syllables. A pair of strong and weak vowels within the *same syllable* are called a diphthong, e.g. [[https://www.spanishdict.com/translate/cuida][cuida]], [[https://www.spanishdict.com/translate/ciudad][ciudad]]. They are also called /gliding vowels/ becaused of how they are pronounced.
* Gender
Spanish nouns have gender. Usually, nouns ending in -o are masculine, like /nacho/, and words ending in -a are feminine like /agua/. This is a general pattern and you will see many exceptions to it. Other patterns will emerge as you learn more Spanish. Be mindful of this pattern as you go.
* Article
The word "the" in Spanish has two forms: /el/ and /la/. The former is used with masculine nouns (e.g. /el profesor/), and the latter on feminine nouns (e.g. /la profesora/). However, when the word begins with a stressed "a" sound, you use /el/ instead of /la/ on singular feminine nouns (e.g. /el agua/ instead of /la agua/; /las aguas/ stay the same).
* Subject Pronouns
Instead of nouns, you can use /subject pronouns/ as the subject of an action. For example, you can say /He ate the apple/ instead of /The trainee ate the apple/. Here is a list of pronouns in Spanish.

| Category                 | Singular            | Plural                  |
|--------------------------+---------------------+-------------------------|
| First person             | yo = I              | nosotros, nosotras = we |
| Second person (informal) | tú (informal) = you | vosotros = you          |
| Second person (formal)   | usted (Ud.) = you   | ustedes (Uds.) = you    |
| Third person             | él = he, ella = she | ellos, ellas = they     |

- Spanish has two different words for "you" based on your familiarity with whomever you are talking to. If you are talking to your friend, family member, or someone younger than you, use /tú/. If you are talking to a stranger or an elder, for example, you should use /usted/ to show respect.
- Note that subject pronouns ending in -a or -as applies to female(s) only! For example, you can only use /ellas/ on a group of women but you need to use /ellos/ when there are men in the group.
* (Regular) Present Tense Verb Conjugation
Like many other languages, you need to conjugate a verb from its /infinitive form/ (e.g. /to swim/ in English or /nadar/ in Spanish) in order to use it (e.g. /he swims/ in English and /él nada/ in Spanish). Spanish verbs end in either /-ar/, /-er/, or /-ir/. How you conjugate the verb depends on the subject pronoun that is appropriate for the person taking the action, and also the ending of the verb. In the table you will find six ways to conjugate verbs (in present tense) with regards to the subject pronoun at hand.

To use the following present tense conjugation table, simply replace the ending (to get the "stem"), and then attach the correct suffix in the corresponding cell.
| Replace...      | /-ar/   | /-er/   | /-ir/   |
|-----------------+-------+-------+-------|
| yo              | -o    | -o    | -o    |
| tú              | -as   | -es   | -es   |
| él/ellas/Ud.    | -a    | -e    | -e    |
| nosotros        | -amos | -emos | -imos |
| vosotros        | -áis  | -éis  | -ís   |
| ellos(-as)/Uds. | -an   | -en   | -en   |
This can take some time to sink in. Try out this [[https://conjuguemos.com/verb/133][Conjuguemos.com activity]] to master present tense verb conjugation!

Examples:
#+BEGIN_QUOTE
Él nada muy bien.
He swims really well.
#+END_QUOTE
#+BEGIN_QUOTE
Yo bebo agua.
I drink water.
#+END_QUOTE
