#+title: Commands (Imperative Mood)
#+author: Landon Park
#+date: 2020-10-04
#+hugo_base_dir: .
#+hugo_custom_front_matter: :toc true
#+hugo_tags: grammar verbs

* Introduction to Commands

In our lives, it is pretty common for us to give commands to others. I'm sure we're all familiar with these two daily ones: "Take your test" or "Turn in your homework." Commands are able to influence the actions of others, which sets the course for a very important linguistic ability.

Both English and Spanish speakers use imperatives all the time. However, there are many versions of the same command based on who you are addressing.

- Tú commands
- Usted (Ud.) commands
- Ustedes (Uds.) commands
- Vosotros commands
- Tips on reflexive commands

* Tú Commands

Pretend you want your friend to eat your lunch. Of course, you could just ask your friend. Or you could use an informal (Tú command).
#+begin_quote
"No tengo hambre. Come mi almuerzo." - I'm not hungry. Eat my lunch.
#+end_quote

Pretend that you don't want your friend to eat your lunch. This is where it gets complicated.
#+begin_quote
"Tengo hambre. No comas mi almuerzo." - I'm hungry. Don't eat my lunch.
#+end_quote

The difference between "Come" and "No comas" demonstrates the affirmative and the negative form of the informal commands. All command forms have an affirmative and a negative type due to the nature of commands (sometimes, you want something to happen and other times you don't). "Come" is affirmative while "No comas" is negative.

** *Affirmative*
Take the el/ella/Ud. present tense conjugation of the verb.
Ex: *Hablar — Habla*

** *Negative*
Remove the stem. If it is an -ar verb, add -es. Otherwise add -as.
Ex: *Hablar — No hables*

Make sure to put "No" before the command since it is negative.

** *Irregular Tú Forms*
As with most things in Spanish, there are irregular forms. These are only *affirmative forms*. Here they are below.
- Ser - Sé
- Ir - Ve
- Ten - Ten
- Ven - Ven
- Hacer - Haz
- Decir - Di
- Poner - Pon
- Salir - Sal

You can remember this with the mnemonic:
*Ten* *Ven*-dors *Pon*-der *Se*-lling *Ve*-ry *Haz*-ardous *Di*-nosaur *Sal*-ami

* Ud. Commands
If you want your teacher to be careful, you would use a formal (Ud.) command.
#+begin_quote
"La ciudad es peligrosa. Tenga cuidado." - The city is dangerous. Be careful.
#+end_quote

Or maybe, you don't want them to leave.
#+begin_quote
"Por favor, ¡no salga de aquí!" - Please don't leave!
#+end_quote

Notice how the affirmative and the negative have essentially the same conjugation. The only difference is whether or not the "No" is placed before the command.

For this command's conjugation, you simply use the el/ella/Ud. form of the present subjunctive.
Ex: Tener — Tenga, Salir — Salga

* Uds. Commands
Now, you are ordering your club members to sell shirts. You use the plural command (Uds.).
#+begin_quote
"Compren las camisas del club" - Sell the club shirts.
#+end_quote

In your class later, you tell your fellow students to not speak so you don't get in trouble.
#+begin_quote
"No hablen de una manera tan ruidosa" - Don't speak in such a loud way.
#+end_quote

Similar to the Ud. commands, the affirmative and the negative have the same conjugation except for the "No" placed before the negative command.

For this command's conjugation, you simply use the third person plural form of the present subjunctive.
Ex: Comprar — Compren, Hablar — Hablen

Keep in mind that cultural contexts matter here. In Spain, Uds. commands would be used to address a group of people that you would address as Usted (for instance, your teachers). However, in any other place, this is used to address any group of people.
* Vosotros Commands
For those using Peninsular Spanish, the vosotros commands are used to order a group of people addressed informally. As review, vosotros is used in Spain when talking to those at an equal or lower social level (essentially, talking to a bunch of people that you address as "Tú").

Pretend that you want to tell a youth choir to sing well.
#+begin_quote
"Niños, cantad bien." - Children, sing well.
#+end_quote

In this affirmative instance, you drop the "r" from the infinitive and add a "d" instead. The verb "ir" does not drop the d, but rather turns into "idos."

Imagine that you suddenly tell them not to drink milk so their voices don't crack.
#+begin_quote
"Niños, no bebáis leche." - Children, do not drink milk.
#+end_quote

In this negative instance, you have to use "No" and then add the vosotros form of the present subjunctive.

** For reflexive verbs:
- Affirmative :: Remove the "r" and then add the reflexive pronoun "os" instead.
  #+begin_quote
  Cepillaos los dientes. - Brush your teeth.
  #+end_quote
- Negative :: Simply add "os" in front of "No."
  #+begin_quote
  No os habléis. Don't talk to yourselves.
  #+end_quote

* Tips on Reflexive Verbs
Ok, you're pretty much set on your regular, run-of-the-mill verbs. But then comes along verbs like hablarse, dormirse and lavarse. We already reviewed what happens to vosotros reflexive commands, but what about the other tenses?

** Affirmative - Attach the reflexive pronoun to the command verb.
#+begin_quote
"Váyase" - "Leave" (Ud. command)
#+end_quote
Make sure to add the accent in order to keep "va" stressed, as in "vaya." We recommend that you [[file:basics.org::*Stress & Accents][brush up on your accent rules]].
** Negative - Put the reflexive pronoun before the command verb.
#+begin_quote
"No se vaya" - "Don't leave" (Ud. command)
#+end_quote
This does not require any accenting like the affirmative conjugation.
* Conclusion
Phew, that should be all on direct commands. There are indirect commands in Spanish, which can be covered another day. Thank you for reading our ESP wiki.
