#+TITLE: Introduction to Spanish
#+AUTHOR: Zhenkai Weng
#+DATE: 2020-09-21
#+BEGIN_OPTIONS
#+STARTUP: hideblocks overview
#+OPTIONS: \n:t
#+HUGO_BASE_DIR: .
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_SECTION: wiki
#+END_OPTIONS

* Introduction
Hello, welcome to English Spanish Partnership's Spanish wiki. [[file:wiki.org][Here]] you can find a series of tutorials on the Spanish language and occasionally on Hispanic culture.

* Why learn Spanish?
- Spanish is the fourth most spoken language in the world.
- Language learning is known to keep your mind sharp and improve your cognitive abilities, including critical thinking, memory, decision-making, etc.
- 20 Spanish speaking countries -- 20 places for travel with unique cultures and art.
- Spanish is considered to be one of the easiest languages for English speakers according to ACTFL.
- You will find a lot of words called /cognates/ that look similar to English words and usually have similar meanings, making your Spanish learning journey easier.
- Chat with your Hispanic friends in Spanish!
