#+TITLE: Introduction to Spanish
#+AUTHOR: Zhenkai Weng
#+DATE: 2020-08-30
#+BEGIN_OPTIONS
#+STARTUP: hideblocks
#+STARTUP: overview
#+OPTIONS: \n:t
#+HUGO_BASE_DIR: .
#+HUGO_CUSTOM_FRONT_MATTER: :toc true
#+HUGO_SECTION: wiki
#+HUGO_TAGS: usage
#+END_OPTIONS

Welcome to the ESP Spanish Wiki! Here's some /essential/ knowledge to kick-start your Spanish learning journey! The first lesson is fairly long, so feel free to take breaks in between.
* Gender
Spanish nouns have gender. Usually, nouns ending in -o are masculine, like /nacho/, and words ending in -a are feminine like /agua/. This is a general pattern and you will see many exceptions to it. Other patterns will emerge as you learn more Spanish. Be mindful of this pattern as you go.
* Article
The word "the" in Spanish has two forms: /el/ and /la/. The former is used on masculine nouns (e.g. /el profesor/), and the latter on feminine nouns (e.g. /la profesora/). However, when the word begins with a stressed "a" sound, you use /el/ instead of /la/ on singular feminine nouns (e.g. /el agua/ instead of /la agua/; /las aguas/ stay the same).
* Subject Pronouns
Instead of nouns, you can use /subject pronouns/ as the subject of an action. For example, you can say /He ate the apple/ instead of /The trainee ate the apple/. Here is a list of pronouns in Spanish.

| Category                 | Singular            | Plural                  |
|--------------------------+---------------------+-------------------------|
| First person             | yo = I              | nosotros, nosotras = we |
| Second person (informal) | tú (informal) = you | vosotros = you          |
| Second person (formal)   | usted (Ud.) = you   | ustedes (Uds.) = you    |
| Third person             | él = he, ella = she | ellos, ellas = they     |

- Spanish has two different words for "you" based on your familiarity with whomever you are talking to. If you are talking to your friend, family member, or someone younger than you, use /tú/. If you are talking to a stranger or an elder, for example, you should use /usted/ to show respect.
- Note that subject pronouns ending in -a or -as applies to female(s) only! For example, you can only use /ellas/ on a group of women but you need to use /ellos/ when there are men in the group.
* Verb conjugation
Like many other languages, you need to conjugate a verb from its /infinitive form/ (e.g. /to swim/ in English or /nadar/ in Spanish) in order to use it (e.g. /he swims/ in English and /él nada/ in Spanish). How you conjugate the verb depends on the subject pronoun that is appropriate for the person taking the action. There are 6 classes of verbs
